import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Function to copy files to dist folder
function copyToDist(files) {
	const distDir = "dist";
	if (!fs.existsSync(distDir)) {
		fs.mkdirSync(distDir, { recursive: true });
	}

	files.forEach((file) => {
		if (fs.existsSync(file)) {
			const fileName = path.basename(file);
			const destPath = path.join(distDir, fileName);
			fs.copyFileSync(file, destPath);
			console.log(`Copied ${file} to ${destPath}`);
		} else {
			console.warn(`Warning: ${file} not found, skipping copy`);
		}
	});
}

const devCopyPlugin = {
	name: "dev-copy",
	setup(build) {
		build.onEnd(() => {
			copyToDevVault();
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
	plugins: prod ? [] : [devCopyPlugin],
});

const devVaultPluginDir = "/home/lonoxx/Documents/Dev-Vault";

function copyToDevVault() {
	if (!fs.existsSync(devVaultPluginDir)) {
		fs.mkdirSync(devVaultPluginDir, { recursive: true });
	}
	["dist/main.js", "manifest.json", "styles.css"].forEach((file) => {
		if (fs.existsSync(file)) {
			const dest = path.join(devVaultPluginDir, path.basename(file));
			fs.copyFileSync(file, dest);
			console.log(`Copied ${file} to ${dest}`);
		}
	});
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	copyToDist(["versions.json", "manifest.json", "styles.css"]);
}
